version: "3.7"
services:
    lookforsimilar:
        container_name: look-for-similar
        ports:
            - '5000:5000'
        networks:
            - ulysses-retrieval
        build:
            dockerfile: Dockerfile
            context: .

networks:
    ulysses-retrieval:
        external: true